input('Nama: ')
input('NIM: ')
input('Kelas Paralel: ')
input('Tempat/Tanggal Lahir: ')
input('Alamat: ')
input('Hobby: ')
input('No.HP: ')

print('Nama: ')
print('NIM: ')
print('Kelas Paralel: ')
print('Tempat/Tanggal Lahir: ') 
print('Alamat: ') 
print('Hobby: ')
print('No.HP: ')