jari_jari=float(input())
tinggi_bejana=float(input())
phi=float(3.14285)
volume= phi* jari_jari*jari_jari*tinggi_bejana
luas=2*phi*jari_jari*(jari_jari+tinggi_bejana)
keliling=2*phi*jari_jari
print("volume = {:.2f}".format (volume))
print("luas = {:.2f}".format(luas))
print("keliling = {:.2f}".format(keliling))